version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync dist s3://spacebitsdotcom
      - aws cloudfront create-invalidation --distribution-id E27NMC5UIA7ZLG --paths "/*"
